export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SCHEDULE_PLAN_NOT_APPROVED: "SCHEDULE_PLAN_NOT_APPROVED",
  SCHEDULE_OUTSIDE_WINDOW: "SCHEDULE_OUTSIDE_WINDOW",
  SCHEDULE_STEP_NOT_PENDING: "SCHEDULE_STEP_NOT_PENDING",
  SCHEDULE_SLOT_OCCUPIED: "SCHEDULE_SLOT_OCCUPIED",
  SCHEDULE_WRITE_FAILED: "SCHEDULE_WRITE_FAILED",
  SCHEDULE_REQUEST_NOT_PENDING: "SCHEDULE_REQUEST_NOT_PENDING",
  SCHEDULE_INVALIDATED: "SCHEDULE_INVALIDATED",
  STEP_NOT_ASSIGNED: "STEP_NOT_ASSIGNED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
